name: cs_quiz_app
description: A beautiful quiz app for CS students to learn efficiently.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Core Flutter packages
  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  google_fonts: ^6.2.1
  http: ^1.2.1
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.1
  uuid: ^4.3.3

  # Firebase
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8
  firebase_storage: ^11.6.9
  google_sign_in: ^6.2.1

  # AI
  google_generative_ai: ^0.4.0

  # File Handling
  file_picker: ^8.0.0+1
  pdf: ^3.10.9
  syncfusion_flutter_pdf: ^30.2.7
  path_provider: ^2.0.15
  path: ^1.8.3

  # UI/UX Packages
  flutter_animate: ^4.5.0
  lottie: ^3.1.0
  
  # Utils
  json_annotation: ^4.9.0
  flutter_dotenv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.0
  json_serializable: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/animations/
    - assets/lesson_data/
