// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQOCgGTTX6_mVGYIufkk2t590TPey-PQ0',
    appId: '1:508170801918:web:ace3ab1fc7db754f7e0baf',
    messagingSenderId: '508170801918',
    projectId: 'fii-smart',
    authDomain: 'fii-smart.firebaseapp.com',
    storageBucket: 'fii-smart.firebasestorage.app',
    measurementId: 'G-1T29VYV7FT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNI92zyQqi8G12_Qeq5M6aSxiL4rvaVWw',
    appId: '1:508170801918:android:b925451e190b9d7a7e0baf',
    messagingSenderId: '508170801918',
    projectId: 'fii-smart',
    storageBucket: 'fii-smart.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjR5ZTszWln57RrUR-08cSTjESJvXEuDE',
    appId: '1:508170801918:ios:ad9fa027218db6c97e0baf',
    messagingSenderId: '508170801918',
    projectId: 'fii-smart',
    storageBucket: 'fii-smart.firebasestorage.app',
    iosBundleId: 'com.example.fiismart',
  );
}
